imports:
- path: service_account.jinja
- path: iam_policy.jinja
- path: bucket_acl.jinja
- path: ubuntu_vm.jinja
{% block imports %}{% endblock %}

resources:
- name: pr-access
  type: service_account.jinja

- name: pr-check
  type: service_account.jinja

- name: pr-bucket
  type: bucket_acl.jinja
  properties:
    nonce: {{ nonce }}
    predefined_acl: private
    
- name: pr-instance
  type: ubuntu_vm.jinja
  properties:
    zone: us-west1-b
    open_external: true


- name: pd1-access
  type: service_account.jinja

- name: pd1-check
  type: service_account.jinja

- name: pd1-bucket
  type: bucket_acl.jinja
  properties:
    nonce: {{ nonce }}
    predefined_acl: private

- name: iam_policy
  type: iam_policy.jinja
  properties:
    bindings:
    - service_account_id: pr-access
      role:
        name: roles/owner

    - service_account_id: pr-check
      role:
        name: roles/iam.roleViewer


    - service_account_id: pd1-access
      role:
        name: roles/storage.admin

    - service_account_id: pd1-check
      role:
        name: roles/iam.roleViewer
        
        
{% block resources %}{% endblock %}

