imports:
- path: service_account.jinja
- path: iam_policy.jinja
- path: bucket_acl.jinja
- path: ubuntu_vm.jinja
- path: cloud_function.jinja

resources:
- name: pr-bucket
  type: bucket_acl.jinja
  properties:
    nonce: {{ nonce }}
    predefined_acl: private
    
- name: pr-instance
  type: ubuntu_vm.jinja
  properties:
    zone: us-west1-b
    open_external: true

- name: pr-f-access
  type: cloud_function.jinja
  properties:
    region: us-central1
    nonce: {{ nonce }}
    entry_point: main
    upload_url: {{ funca_upload_url_pr }}
    policyBindings:
    - role: roles/cloudfunctions.invoker
      service_account_id: allusers
    env_variables: {"NONCE":{{nonce}},"RESOURCE_PREFIX":{{resource_prefix_pr}},"LEVEL_NAME":{{level_name_pr}}}

- name: pr-f-check
  type: cloud_function.jinja
  properties:
    region: us-central1
    nonce: {{ nonce }}
    entry_point: main
    upload_url: {{ funcc_upload_url_pr }}
    policyBindings:
    - role: roles/cloudfunctions.invoker
      service_account_id: allusers
    env_variables:  {"NONCE":{{nonce}},"RESOURCE_PREFIX":{{resource_prefix_pr}},"LEVEL_NAME":{{level_name_pr}}}


- name: pd1-bucket
  type: bucket_acl.jinja
  properties:
    nonce: {{ nonce }}
    predefined_acl: private

- name: pd1-f-access
  type: cloud_function.jinja
  properties:
    region: us-central1
    nonce: {{ nonce }}
    entry_point: main
    upload_url: {{ funca_upload_url_pd1 }}
    policyBindings:
    - role: roles/cloudfunctions.invoker
      service_account_id: allusers
    env_variables: {"NONCE":{{nonce}},"RESOURCE_PREFIX":{{resource_prefix_pd1}},"LEVEL_NAME":{{level_name_pd1}}}

- name: pd1-f-check
  type: cloud_function.jinja
  properties:
    region: us-central1
    nonce: {{ nonce }}
    entry_point: main
    upload_url: {{ funcc_upload_url_pd1 }}
    policyBindings:
    - role: roles/cloudfunctions.invoker
      service_account_id: allusers
    env_variables: {"NONCE":{{nonce}},"RESOURCE_PREFIX":{{resource_prefix_pd1}},"LEVEL_NAME":{{level_name_pd1}}}


- name: pd2-instance
  type: ubuntu_vm.jinja
  properties:
    zone: us-west1-b
    open_external: true

- name: pd2-f-access
  type: cloud_function.jinja
  properties:
    region: us-central1
    nonce: {{ nonce }}
    entry_point: main
    upload_url: {{ funca_upload_url_pd2 }}
    policyBindings:
    - role: roles/cloudfunctions.invoker
      service_account_id: allusers
    env_variables: {"NONCE":{{nonce}},"RESOURCE_PREFIX":{{resource_prefix_pd2}},"LEVEL_NAME":{{level_name_pd2}}}

- name: pd2-f-check
  type: cloud_function.jinja
  properties:
    region: us-central1
    nonce: {{ nonce }}
    entry_point: main
    upload_url: {{ funcc_upload_url_pd2 }}
    policyBindings:
    - role: roles/cloudfunctions.invoker
      service_account_id: allusers
    env_variables: {"NONCE":{{nonce}},"RESOURCE_PREFIX":{{resource_prefix_pd2}},"LEVEL_NAME":{{level_name_pd2}}}


- name: pd3-f-access
  type: cloud_function.jinja
  properties:
    region: us-central1
    nonce: {{ nonce }}
    entry_point: main
    upload_url: {{ funca_upload_url_pd3 }}
    policyBindings:
    - role: roles/cloudfunctions.invoker
      service_account_id: allusers
    env_variables: {"NONCE":{{nonce}},"RESOURCE_PREFIX":{{resource_prefix_pd3}},"LEVEL_NAME":{{level_name_pd3}}}

- name: pd3-f-check
  type: cloud_function.jinja
  properties:
    region: us-central1
    nonce: {{ nonce }}
    entry_point: main
    upload_url: {{ funcc_upload_url_pd3 }}
    policyBindings:
    - role: roles/cloudfunctions.invoker
      service_account_id: allusers
    env_variables: {"NONCE":{{nonce}},"RESOURCE_PREFIX":{{resource_prefix_pd3}},"LEVEL_NAME":{{level_name_pd3}}}


- name: pd4-f-access
  type: cloud_function.jinja
  properties:
    region: us-central1
    nonce: {{ nonce }}
    entry_point: main
    upload_url: {{ funca_upload_url_pd4 }}
    policyBindings:
    - role: roles/cloudfunctions.invoker
      service_account_id: allusers
    env_variables: {"NONCE":{{nonce}},"RESOURCE_PREFIX":{{resource_prefix_pd4}},"LEVEL_NAME":{{level_name_pd4}}}

- name: pd4-f-check
  type: cloud_function.jinja
  properties:
    region: us-central1
    nonce: {{ nonce }}
    entry_point: main
    upload_url: {{ funcc_upload_url_pd4 }}
    policyBindings:
    - role: roles/cloudfunctions.invoker
      service_account_id: allusers
    env_variables: {"NONCE":{{nonce}},"RESOURCE_PREFIX":{{resource_prefix_pd4}},"LEVEL_NAME":{{level_name_pd4}}}

- name: pd5-bucket
  type: bucket_acl.jinja
  properties:
    nonce: {{ nonce }}
    predefined_acl: private

- name: pd5-f-access
  type: cloud_function.jinja
  properties:
    region: us-central1
    nonce: {{ nonce }}
    entry_point: main
    upload_url: {{ funca_upload_url_pd5 }}
    policyBindings:
    - role: roles/cloudfunctions.invoker
      service_account_id: allusers
    env_variables: {"NONCE":{{nonce}},"RESOURCE_PREFIX":{{resource_prefix_pd5}},"LEVEL_NAME":{{level_name_pd5}}}

- name: pd5-f-check
  type: cloud_function.jinja
  properties:
    region: us-central1
    nonce: {{ nonce }}
    entry_point: main
    upload_url: {{ funcc_upload_url_pd5 }}
    policyBindings:
    - role: roles/cloudfunctions.invoker
      service_account_id: allusers
    env_variables: {"NONCE":{{nonce}},"RESOURCE_PREFIX":{{resource_prefix_pd5}},"LEVEL_NAME":{{level_name_pd5}}}


- name: ct1-bucket
  type: bucket_acl.jinja
  properties:
    nonce: {{ nonce }}
    predefined_acl: private

- name: ct1-instance
  type: ubuntu_vm.jinja
  properties:
    zone: us-west1-b
    open_external: true

- name: ct1-f-access
  type: cloud_function.jinja
  properties:
    region: us-central1
    nonce: {{ nonce }}
    entry_point: main
    upload_url: {{ funca_upload_url_ct1 }}
    policyBindings:
    - role: roles/cloudfunctions.invoker
      service_account_id: allusers
    env_variables: {"NONCE":{{nonce}},"RESOURCE_PREFIX":{{resource_prefix_ct1}},"LEVEL_NAME":{{level_name_ct1}}}

- name: ct1-f-check
  type: cloud_function.jinja
  properties:
    region: us-central1
    nonce: {{ nonce }}
    entry_point: main
    upload_url: {{ funcc_upload_url_ct1 }}
    policyBindings:
    - role: roles/cloudfunctions.invoker
      service_account_id: allusers
    env_variables: {"NONCE":{{nonce}},"RESOURCE_PREFIX":{{resource_prefix_ct1}},"LEVEL_NAME":{{level_name_ct1}}}

- name: ct2-bucket
  type: bucket_acl.jinja
  properties:
    nonce: {{ nonce }}
    predefined_acl: private

- name: ct2-f-access
  type: cloud_function.jinja
  properties:
    region: us-central1
    nonce: {{ nonce }}
    entry_point: main
    upload_url: {{ funca_upload_url_ct2 }}
    policyBindings:
    - role: roles/cloudfunctions.invoker
      service_account_id: allusers
    env_variables: {"NONCE":{{nonce}},"RESOURCE_PREFIX":{{resource_prefix_ct2}},"LEVEL_NAME":{{level_name_ct2}}}

- name: ct2-f-check
  type: cloud_function.jinja
  properties:
    region: us-central1
    nonce: {{ nonce }}
    entry_point: main
    upload_url: {{ funcc_upload_url_ct2 }}
    policyBindings:
    - role: roles/cloudfunctions.invoker
      service_account_id: allusers
    env_variables: {"NONCE":{{nonce}},"RESOURCE_PREFIX":{{resource_prefix_ct2}},"LEVEL_NAME":{{level_name_ct2}}}

- name: ct3-instance
  type: ubuntu_vm.jinja
  properties:
    zone: us-west1-b
    open_external: true

- name: ct3-f-access
  type: cloud_function.jinja
  properties:
    region: us-central1
    nonce: {{ nonce }}
    entry_point: main
    upload_url: {{ funca_upload_url_ct3 }}
    policyBindings:
    - role: roles/cloudfunctions.invoker
      service_account_id: allusers
    env_variables: {"NONCE":{{nonce}},"RESOURCE_PREFIX":{{resource_prefix_ct3}},"LEVEL_NAME":{{level_name_ct3}}}

- name: ct3-f-check
  type: cloud_function.jinja
  properties:
    region: us-central1
    nonce: {{ nonce }}
    entry_point: main
    upload_url: {{ funcc_upload_url_ct3 }}
    policyBindings:
    - role: roles/cloudfunctions.invoker
      service_account_id: allusers
    env_variables: {"NONCE":{{nonce}},"RESOURCE_PREFIX":{{resource_prefix_ct3}},"LEVEL_NAME":{{level_name_ct3}}}

- name: ct4-f-access
  type: cloud_function.jinja
  properties:
    region: us-central1
    nonce: {{ nonce }}
    entry_point: main
    upload_url: {{ funca_upload_url_ct4 }}
    policyBindings:
    - role: roles/cloudfunctions.invoker
      service_account_id: allusers
    env_variables: {"NONCE":{{nonce}},"RESOURCE_PREFIX":{{resource_prefix_ct4}},"LEVEL_NAME":{{level_name_ct4}}}

- name: ct4-f-check
  type: cloud_function.jinja
  properties:
    region: us-central1
    nonce: {{ nonce }}
    entry_point: main
    upload_url: {{ funcc_upload_url_ct4 }}
    policyBindings:
    - role: roles/cloudfunctions.invoker
      service_account_id: allusers
    env_variables: {"NONCE":{{nonce}},"RESOURCE_PREFIX":{{resource_prefix_ct4}},"LEVEL_NAME":{{level_name_ct4}}}


- name: ct5-bucket
  type: bucket_acl.jinja
  properties:
    nonce: {{ nonce }}
    predefined_acl: private

- name: ct5-f-access
  type: cloud_function.jinja
  properties:
    region: us-central1
    nonce: {{ nonce }}
    entry_point: main
    upload_url: {{ funca_upload_url_ct5 }}
    policyBindings:
    - role: roles/cloudfunctions.invoker
      service_account_id: allusers
    env_variables: {"NONCE":{{nonce}},"RESOURCE_PREFIX":{{resource_prefix_ct5}},"LEVEL_NAME":{{level_name_ct5}}}

- name: ct5-f-check
  type: cloud_function.jinja
  properties:
    region: us-central1
    nonce: {{ nonce }}
    entry_point: main
    upload_url: {{ funcc_upload_url_ct5 }}
    policyBindings:
    - role: roles/cloudfunctions.invoker
      service_account_id: allusers
    env_variables: {"NONCE":{{nonce}},"RESOURCE_PREFIX":{{resource_prefix_ct5}},"LEVEL_NAME":{{level_name_ct5}}}

- name: scores-f
  type: cloud_function.jinja
  properties:
    region: us-central1
    nonce: {{ nonce }}
    entry_point: main
    upload_url: {{ funcc_upload_url_scores }}
    policyBindings:
    - role: roles/cloudfunctions.invoker
      service_account_id: allusers
    env_variables: {"NONCE":{{nonce}}, "LOGIN_USER":{{login_user}}}


- name: iam_policy
  type: iam_policy.jinja
  properties:
    bindings:
    - service_account_id: pr-f-access-{{nonce}}-sa
      role:
        name: roles/owner

    - service_account_id: pr-f-check-{{nonce}}-sa
      role:
        name: roles/iam.roleViewer


    - service_account_id: pd1-f-access-{{nonce}}-sa
      role:
        name: roles/storage.admin

    - service_account_id: pd1-f-check-{{nonce}}-sa
      role:
        name: roles/iam.roleViewer


    - service_account_id: pd2-f-access-{{nonce}}-sa
      role:
        name: roles/compute.admin

    - service_account_id: pd2-f-check-{{nonce}}-sa
      role:
        name: roles/iam.roleViewer



    - service_account_id: pd3-f-access-{{nonce}}-sa
      role:
        name: roles/logging.admin

    - service_account_id: pd3-f-check-{{nonce}}-sa
      role:
        name: roles/iam.roleViewer


    - service_account_id: pd4-f-access-{{nonce}}-sa
      role:
        name: roles/datastore.owner

    - service_account_id: pd4-f-check-{{nonce}}-sa
      role:
        name: roles/iam.roleViewer
    
    - service_account_id: pd5-f-access-{{nonce}}-sa
      role:
        name: roles/owner

    - service_account_id: pd5-f-check-{{nonce}}-sa
      role:
        name: roles/iam.roleViewer



    - service_account_id: ct1-f-access-{{nonce}}-sa
      role:
        name: roles/owner

    - service_account_id: ct1-f-check-{{nonce}}-sa
      role:
        name: custom
        custom_nonce: {{ nonce }}
        permissions:
        - iam.roles.list
        - resourcemanager.projects.getIamPolicy
    
    - service_account_id: ct2-f-access-{{nonce}}-sa
      role:
        name: roles/storage.admin

    - service_account_id: ct2-f-check-{{nonce}}-sa
      role:
        name: custom
        custom_nonce: {{ nonce }}
        permissions:
        - iam.roles.list
        - resourcemanager.projects.getIamPolicy


    - service_account_id: ct3-f-access-{{nonce}}-sa
      role:
        name: roles/compute.admin

    - service_account_id: ct3-f-check-{{nonce}}-sa
      role:
        name: custom
        custom_nonce: {{ nonce }}
        permissions:
        - iam.roles.list
        - resourcemanager.projects.getIamPolicy

    - service_account_id: ct4-f-access-{{nonce}}-sa
      role:
        name: roles/logging.admin

    - service_account_id: ct4-f-check-{{nonce}}-sa
      role:
        name: custom
        custom_nonce: {{ nonce }}
        permissions:
        - iam.roles.list
        - resourcemanager.projects.getIamPolicy

    - service_account_id: ct5-f-access-{{nonce}}-sa
      role:
        name: roles/storage.admin

    - service_account_id: ct5-f-access-{{nonce}}-sa
      role:
        name: roles/datastore.owner

    - service_account_id: ct5-f-check-{{nonce}}-sa
      role:
        name: custom
        custom_nonce: {{ nonce }}
        permissions:
        - iam.roles.list
        - iam.roles.get
        - resourcemanager.projects.getIamPolicy

    - service_account_id: scores-f-{{nonce}}-sa
      role:
        name: custom
        custom_nonce: {{ nonce }}
        permissions:
        - iam.roles.list
        - resourcemanager.projects.getIamPolicy




