imports:
- path: service_account.jinja
- path: iam_policy.jinja
- path: bucket_acl.jinja
- path: ubuntu_vm.jinja
{% block imports %}{% endblock %}

resources:
- name: pr-access
  type: service_account.jinja

- name: pr-check
  type: service_account.jinja

- name: pr-bucket
  type: bucket_acl.jinja
  properties:
    nonce: {{ nonce }}
    predefined_acl: private
    
- name: pr-instance
  type: ubuntu_vm.jinja
  properties:
    zone: us-west1-b
    open_external: true


- name: pd1-access
  type: service_account.jinja

- name: pd1-check
  type: service_account.jinja

- name: pd1-bucket
  type: bucket_acl.jinja
  properties:
    nonce: {{ nonce }}
    predefined_acl: private


- name: pd2-access
  type: service_account.jinja

- name: pd2-check
  type: service_account.jinja

- name: pd2-instance
  type: ubuntu_vm.jinja
  properties:
    zone: us-west1-b
    open_external: true

- name: pd3-access
  type: service_account.jinja

- name: pd3-check
  type: service_account.jinja


- name: pd4-access
  type: service_account.jinja

- name: pd4-check
  type: service_account.jinja


- name: ct1-access
  type: service_account.jinja

- name: ct1-check
  type: service_account.jinja

- name: ct1-bucket
  type: bucket_acl.jinja
  properties:
    nonce: {{ nonce }}
    predefined_acl: private

- name: ct1-instance
  type: ubuntu_vm.jinja
  properties:
    zone: us-west1-b
    open_external: true

- name: ct2-access
  type: service_account.jinja

- name: ct2-check
  type: service_account.jinja

- name: ct2-bucket
  type: bucket_acl.jinja
  properties:
    nonce: {{ nonce }}
    predefined_acl: private

- name: ct3-access
  type: service_account.jinja

- name: ct3-check
  type: service_account.jinja

- name: ct3-instance
  type: ubuntu_vm.jinja
  properties:
    zone: us-west1-b
    open_external: true

- name: ct4-access
  type: service_account.jinja

- name: ct4-check
  type: service_account.jinja


    


- name: iam_policy
  type: iam_policy.jinja
  properties:
    bindings:
    - service_account_id: pr-access
      role:
        name: roles/owner

    - service_account_id: pr-check
      role:
        name: roles/iam.roleViewer


    - service_account_id: pd1-access
      role:
        name: roles/storage.admin

    - service_account_id: pd1-check
      role:
        name: roles/iam.roleViewer


    - service_account_id: pd2-access
      role:
        name: roles/compute.admin

    - service_account_id: pd2-check
      role:
        name: roles/iam.roleViewer



    - service_account_id: pd3-access
      role:
        name: roles/logging.admin

    - service_account_id: pd3-check
      role:
        name: roles/iam.roleViewer


    - service_account_id: pd4-access
      role:
        name: roles/datastore.owner

    - service_account_id: pd4-check
      role:
        name: roles/iam.roleViewer



    - service_account_id: ct1-access
      role:
        name: roles/owner

    - service_account_id: ct1-check
      role:
        name: custom
        custom_nonce: {{ nonce }}
        permissions:
        - iam.roles.list
        - resourcemanager.projects.getIamPolicy
    
    - service_account_id: ct2-access
      role:
        name: roles/storage.admin

    - service_account_id: ct2-check
      role:
        name: custom
        custom_nonce: {{ nonce }}
        permissions:
        - iam.roles.list
        - resourcemanager.projects.getIamPolicy


    - service_account_id: ct3-access
      role:
        name: roles/compute.admin

    - service_account_id: ct3-check
      role:
        name: custom
        custom_nonce: {{ nonce }}
        permissions:
        - iam.roles.list
        - resourcemanager.projects.getIamPolicy

    - service_account_id: ct4-access
      role:
        name: roles/logging.admin

    - service_account_id: ct4-check
      role:
        name: custom
        custom_nonce: {{ nonce }}
        permissions:
        - iam.roles.list
        - resourcemanager.projects.getIamPolicy

    
        
        
{% block resources %}{% endblock %}

