{% extends 'roles.yaml' %}

{% block imports %}
- path: cloud_function.jinja
{% endblock %}

{% block resources %}
- name: pr-f-access
  type: cloud_function.jinja
  properties:
    region: us-central1
    nonce: {{ nonce }}
    entry_point: main
    upload_url: {{ funca_upload_url_pr }}
    policyBindings:
    - role: roles/cloudfunctions.invoker
      service_account_id: allusers
    env_variables: {"NONCE":{{nonce}},"RESOURCE_PREFIX":{{resource_prefix_pr}},"LEVEL_NAME":{{level_name_pr}}}

- name: pr-f-check
  type: cloud_function.jinja
  properties:
    region: us-central1
    nonce: {{ nonce }}
    entry_point: main
    upload_url: {{ funcc_upload_url_pr }}
    policyBindings:
    - role: roles/cloudfunctions.invoker
      service_account_id: allusers
    env_variables:  {"NONCE":{{nonce}},"RESOURCE_PREFIX":{{resource_prefix_pr}},"LEVEL_NAME":{{level_name_pr}}}


- name: pd1-f-access
  type: cloud_function.jinja
  properties:
    region: us-central1
    nonce: {{ nonce }}
    entry_point: main
    upload_url: {{ funca_upload_url_pd1 }}
    policyBindings:
    - role: roles/cloudfunctions.invoker
      service_account_id: allusers
    env_variables: {"NONCE":{{nonce}},"RESOURCE_PREFIX":{{resource_prefix_pd1}},"LEVEL_NAME":{{level_name_pd1}}}

- name: pd1-f-check
  type: cloud_function.jinja
  properties:
    region: us-central1
    nonce: {{ nonce }}
    entry_point: main
    upload_url: {{ funcc_upload_url_pd1 }}
    policyBindings:
    - role: roles/cloudfunctions.invoker
      service_account_id: allusers
    env_variables: {"NONCE":{{nonce}},"RESOURCE_PREFIX":{{resource_prefix_pd1}},"LEVEL_NAME":{{level_name_pd1}}}


{% endblock %}
